# Generated by Django 4.0.2 on 2022-02-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('link', models.URLField(max_length=255)),
                ('summary', models.TextField()),
                ('pub_date', models.DateField(help_text='DD/MM/YYYY', verbose_name='date published')),
                ('slug', models.SlugField(help_text='A label for URL config.', max_length=63, unique=True, verbose_name='user friendly url')),
            ],
            options={
                'verbose_name': 'article',
                'ordering': ['-pub_date'],
                'get_latest_by': 'pub_date',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=31)),
                ('slug', models.SlugField(help_text='A label for URL config.', max_length=31, unique=True, verbose_name='user friendly url')),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(help_text='Project website', max_length=255)),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='date added')),
                ('image', models.ImageField(default='project_default.jpg', upload_to='project_pic')),
                ('telegram_id', models.CharField(blank=True, default='username', help_text="please input project's telegram id", max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Project',
                'ordering': ['title'],
                'get_latest_by': 'date_added',
            },
        ),
    ]
